/*
 * generated by Xtext
 */
package protolipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProtobufUiModule extends protolipse.ui.AbstractProtobufUiModule {
	public ProtobufUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
