/*
 * generated by Xtext
 */
package protolipse.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import protolipse.ui.internal.ProtobufActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProtobufExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProtobufActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProtobufActivator.getInstance().getInjector(ProtobufActivator.PROTOLIPSE_PROTOBUF);
	}
	
}
