/*
 * generated by Xtext
 */
package protolipse.ui.contentassist

import protolipse.ui.contentassist.AbstractProtobufProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ProtobufProposalProvider extends AbstractProtobufProposalProvider {
}
