/*
 * generated by Xtext
 */
package protolipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProtobufRuntimeModule extends protolipse.AbstractProtobufRuntimeModule {

}
