/*
 * generated by Xtext
 */
package protolipse;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ProtobufStandaloneSetup extends ProtobufStandaloneSetupGenerated{

	public static void doSetup() {
		new ProtobufStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

